# Check Lua Formatting
name: Check Lua Formatting
on: pull_request_target

jobs:
  stylua-check:
    if: github.repository == 'Melis-Pablo/kickstart.nvim'
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

# ***************************************************************************
# **NOTE**
# Please verify that the `base repository` above has the intended destination!
# Github by default opens Pull Requests against the parent of a forked repository.
# If this is your personal fork and you didn't intend to open a PR for contribution
# to the original project then adjust the `base repository` accordingly.
# **************************************************************************
